### ISSUE TITLE
Unable to execute gradle msbuild task

### ISSUE THREAD

**Issue by sreesake** [Itiviti/gradle-msbuild-plugin#122]
I am running gradle 6.4.1 and trying to use older version 2.9 of gradle-msbuild-plugin. It's a limitation due to corporate firewall.

When I execute gradle msbuild, I keep having error saying 
Cannot cast object 'null (Output)' with class 'org.gradle.api.internal.tasks.DefaultTaskOutputFilePropertyRegistration' to class 'org.gradle.api.tasks.TaskOutputs'
![error](https://user-images.githubusercontent.com/80283336/110368015-737ade00-8016-11eb-9d5f-e4e076fa0e64.jpeg)

My build.gradle file is barebones with just repo info and solution filename, targets and destinationDir in msbuild config section.

**Comment by ngyukman** [comment]
hi @sreesake 

not sure if you still have this issue in latest version, but if that's the case can you try with `--stacktrace` to see where is the problem?
it seems to be related to line 25 in build.gradle
