### ISSUE TITLE
Locating MSBUILD fails if multiple installed versions match version range

### ISSUE THREAD

**Issue by freudi74** [Itiviti/gradle-msbuild-plugin#123]
I know you claim the project deprecated in favor of the dotnet plugin, but I find it very useful to build MSVC++ projects from gradle.
I have recently encountered a problem, though.

When you select a version range, and multiple installed versions that are detected by vswhere satisfy that version range, then the plugin fails. Root cause seems to be, that when setting a version, the MSBuildResolver.findMsbuildByVsWhere() is not adding the "-latest" to the call to vswhere, but the handling of the results from the command line expects only one instance to be reported by vswhere. Combining "-version ..." with "-latest" would work perfectly fine.

**Comment by ngyukman** [comment]
hi @freudi74 

the plugin doesn't really support a version range when specified in the msbuild version
as per code if the version is not specified it take the latest already which should suit most of the use case
what is the reason behind having both version range in the build.gradle while couldn't just use latest?

**Comment by ngyukman** [comment]
thanks for your explanation

**Comment by ngyukman** [comment]
Fixes in https://github.com/Itiviti/gradle-msbuild-plugin/commit/bccd066669b7a33b025f1d68ece53722087279c3
